version: '3'
services:
  ftp:
    image: atmoz/sftp
    ports:
        - 22:22/tcp
    volumes:
      - ./users.conf:/etc/sftp/users.conf:ro
      - ./data:/data
      - ./bindmount.sh:/etc/sftp.d/bindmount.sh
    cap_add:
      - SYS_ADMIN